#import "@preview/elsearticle:2.0.0": *
== Linear power drain

The more interesting property of power drain function, that is fully linear with respect to usage(it have form $p(u)= k * u$) this implies some properties you probably should know.

Imagine situation, you have 2 active threads. You should close left door for 1 second, and right door also for 1 second($x$ amount of closed doors is $x$ usage, same as in UCN : Recode). What the best method to optimive power drain in that situation?
- Close the doors together.
- Close the doors separately (close left $->$ open left $->$ close right $->$ open right).
- Something more complex, combining first 2 methods (close left $->$ after $x$ time close right $->$ close left $->$ close right).

For now we can breakdown all those methods.

If we chose close doors together, we will have 2 usage for 1 second, our total power drain will be (Eq. @eqpowermethod1).

$ p(1 + 1) = p(2) $ <eqpowermethod1>

If we chose close doors separately, we will have 1 usage for 2 seconds(first second we have left door closed, last second we have right door closed) (Eq. @eqpowermethod2).

$ p(1) + p(1) = 2p(1) $ <eqpowermethod2>

Third method is actually a generalization of first two methods. Suppose $x, 0<=x<=1$, we will close the right door in $x$ seconds after closing the left door. If $x = 0$, we get first case, closing doors together. If $x = 1$, we get second case, closing doors separately. So now our task is to find optimal value $x$ where power drain will be lowest.

#figure(
  image("../images/powermethod3.png"),
  caption : [accurate and professional illustration of the door closing process depending on $x$]
) <powermethod3fig>

As you can se in picture @powermethod3fig, we have 2 sections with 1 usage for $x$ seconds, and 1 section with 2 usage for $1-2x$ seconds (Eq. @eqpowermethod3):

$ x p(1) + (1-x)p(2) + x p(1) = 2x p(1) + (1-x)p(2) $ <eqpowermethod3>

The result now depends only on the nature of the function’s operation. To solve the problem in the general case, we would need to find the minimum of the expression using its derivative by x, but in our case it is sufficient to simply substitute the expression $p(u)=k u$, using fact that our function is `linear` with respect to usage (Eq. @eqpowermethod31).

$ 2x p(1) + (1-x)p(2) = 2x k + (1-x)2k = 2x k + 2k - 2x k = 2k $ <eqpowermethod31>

We simplyfy the expresison, and got an answer independent of $x$, using only fact that our power drain function is linear. That means whatever $x$ value will be, or whatever door stratery we will use, our power drain always be the same. This property follows from the fact that energy drain is energy usage multiplied by a constant; therefore, $p(x) = x p(1)$. For comparison, in the original UCN the power drain is quadratic $p(u) = a u^2$. in the same way, it can be shown that in valilla the most efficent way is close doors separately, so you should minimize power usage.

So overall in Recode we shouldn't care about high usage at all, problem with energy will be if you bad with opening doors timings or overusing tools (using gmb when lefty has 0 progress, AC/fan when temp is 60)

== Power generator is useless?

Basic ultimatum tool strategy, is basically cycling `[ PG + Fan -> SV -> GMB ]`, you cant survive without cooling or GMB for lefty, but how power generator helps you powerwise? Ofc we will calculate it for hard mode and for all animatronics on 20 AI.

Imagine you will use power generator some amount of time, thus Music Man progresses by some value. And to decrease his progress you will use silent ventilation to decrease all that progress.The result will be the difference between the power generated by the PG and the power drain of SV.

For $t_(g e n)$ seconds of PG you get $t_(g e n) dot p_(g e n)$ power percentage, PG works with 2 noice, so music man progress by $t_(g e n)t dot m_(h m)(2, 20)$ value.

Now we will find how much we should use SV to neutralize all that progress, formally solve the equation $t_(s v) dot m^(s v)_(h m) + t_(g e n) dot m_(h m)(2, 20) = 0$ to find $t_(s v)$(Eq. @pgenus:tsv:eq)

$ t_(s v) = -(t_(g e n) dot m_(h m)(2, 20))/(m^(s v)_(h m)) $ <pgenus:tsv:eq>

And then amount of power we will lost from SV will be $t_(s v) dot p_(h m)(1)$. After all that we have(Eq. @pgenus:pgtotal:eq, @pgenus:svtotal:eq)

$ t_(g e n) dot p_(g e n) = 0.054t_(g e n) $ <pgenus:pgtotal:eq>
$ t_(s v) dot p_(h m)(1) = -(p_(h m)(1) dot t_(g e n) dot m_(h m)(2, 20))/(m^(s v)_(h m)) =\ = -(-0.2337t dot 1.8)/(-6.9) approx - 0.061t $<pgenus:svtotal:eq>

We got that power drain for SV exceeds PG. However Music Man has progress decrease when there is no noice, maybe it helps decreasing Music Man progress? Well, no. If you play without PG and fan, using AC for coolingm, making minimal noice, playing perfectly with Lolbit and Phone Guy, Music Man still will be progress by AC noice. His calming down on hard mode is disproportionately small, compared to the progress gain. So there is no way to globally calm MM without using SV. That fact already makes 'old' strategy unoptimal powerwise. 

But this doesnt completely mean that PG is useless. It becomes useless when the player forced to calm down the Music Man using SV. The most optimal strategy for using PG is to use it only as much as necessary to avoid getting Music Man to his max aggression until the end of the night, using SV only for his special attacks.

== Music Man abuse

From the previous paragraph you learned that many conditions are needed for the rational use of PG. But there is another advanced technique that allows you to make as much noise as you want without any Music Man progression. 

There is one thing during his special attack, progress cap in $[20;80]$ range. So if Music Man is on 20 progress, you cant lower that value until you counter his special attack. And its the same for 80 progression. Вuring his special attack, regardless of the noise level, progress wont go up above 80. Therefore, the point of 'Music Man abuse' is to use noise tools(mainly PG + Fan) to the maximum during this time without any consequences, with perfect execution and rng, you can generate up to $10p_(g e n) = 0.54$ enegry.

It sounds simple, but in reality it will be difficult to do this in a regular run.

In addition, i consider 2 types of use of this technique - single use and constant throughout the night:
- In the first case you play night like normal, knowing that MM progresses over time, you can only make one abuse at the end of the night, this gives an obvious advantage compared to not making this abuse. 
- In second case case, the strategy is to get to 80 Muisc Man progress as quickly as possible, and then abuse every special attack. The problem is that after each special attack you will have to use SV, for making next abuse possible, and it is a very good question whether the abuse in the long term gives more energy than you spend on SV. (Im too lazy to calculate it, and in general playing with such a strategy is much more difficult)

== 5 AM power optimizations

=== Lefty

=== Jack-O-Chica

=== General

== Powerpace formula

