#import "@preview/elsearticle:2.0.0": *
== Linear power drain

The more interesting property of power drain function, that is fully linear with respect to usage(it have form $p(u)= k * u$) this implies some properties you probably should know.

Imagine situation, you have 2 active threads. You should close left door for 1 second, and right door also for 1 second($x$ amount of closed doors is $x$ usage, same as in UCN : Recode). What the best method to optimive power drain in that situation?
- Close the doors together.
- Close the doors separately (close left $->$ open left $->$ close right $->$ open right).
- Something more complex, combining first 2 methods (close left $->$ after $x$ time close right $->$ close left $->$ close right).

For now we can breakdown all those methods.

If we chose close doors together, we will have 2 usage for 1 second, our total power drain will be (Eq. @eqpowermethod1).

$ p(1 + 1) = p(2) $ <eqpowermethod1>

If we chose close doors separately, we will have 1 usage for 2 seconds(first second we have left door closed, last second we have right door closed) (Eq. @eqpowermethod2).

$ p(1) + p(1) = 2p(1) $ <eqpowermethod2>

Third method is actually a generalization of first two methods. Suppose $x, 0<=x<=1$, we will close the right door in $x$ seconds after closing the left door. If $x = 0$, we get first case, closing doors together. If $x = 1$, we get second case, closing doors separately. So now our task is to find optimal value $x$ where power drain will be lowest.

#figure(
  image("../images/powermethod3.png"),
  caption : [accurate and professional illustration of the door closing process depending on $x$]
) <powermethod3fig>

As you can se in picture @powermethod3fig, we have 2 sections with 1 usage for $x$ seconds, and 1 section with 2 usage for $1-2x$ seconds (Eq. @eqpowermethod3):

$ x p(1) + (1-x)p(2) + x p(1) = 2x p(1) + (1-x)p(2) $ <eqpowermethod3>

The result now depends only on the nature of the function’s operation. To solve the problem in the general case, we would need to find the minimum of the expression using its derivative by x, but in our case it is sufficient to simply substitute the expression $p(u)=k u$, using fact that our function is `linear` with respect to usage (Eq. @eqpowermethod31).

$ 2x p(1) + (1-x)p(2) = 2x k + (1-x)2k = 2x k + 2k - 2x k = 2k $ <eqpowermethod31>

We simplyfy the expresison, and got an answer independent of $x$, using only fact that our power drain function is linear. That means whatever $x$ value will be, or whatever door stratery we will use, our power drain always be the same. This property follows from the fact that energy drain is energy usage multiplied by a constant; therefore, $p(x) = x p(1)$. For comparison, in the original UCN the power drain is quadratic $p(u) = a u^2$. in the same way, it can be shown that in valilla the most efficent way is close doors separately, so you should minimize power usage.

So overall in Recode we shouldn't care about high usage at all, you can use tools combo like ``, problem with energy will be if you bad with opening doors timings or overusing tools (using GMB when lefty has 0 progress, AC/fan when temp is 60)

== Power generator is useless?

Basic ultimatum tool strategy, is cycling `[ PG + Fan -> SV -> GMB ]`, you cant survive without cooling or GMB for lefty, but how power generator helps you powerwise? Ofc we will calculate it for hard mode and for all animatronics on 20 AI.

Imagine you will use power generator some amount of time, thus Music Man progresses by some value. And to decrease his progress you will use silent ventilation to decrease all that progress.The result will be the difference between the power generated by the PG and the power drain of SV.

For $t_(g e n)$ seconds of PG you get $t_(g e n) dot p_(g e n)$ power percentage, PG works with 2 noice, so music man progress by $t_(g e n)t dot m_(h m)(2, 20)$ value.

Now we will find how much we should use SV to neutralize all that progress, formally solve the equation $t_(s v) dot m^(s v)_(h m) + t_(g e n) dot m_(h m)(2, 20) = 0$ to find $t_(s v)$(Eq. @pgenus:tsv:eq)

$ t_(s v) = -(t_(g e n) dot m_(h m)(2, 20))/(m^(s v)_(h m)) $ <pgenus:tsv:eq>

And then amount of power we will lost from SV will be $t_(s v) dot p_(h m)(1)$. After all that we have(Eq. @pgenus:pgtotal:eq, @pgenus:svtotal:eq)

$ t_(g e n) dot p_(g e n) = 0.054t_(g e n) $ <pgenus:pgtotal:eq>
$ t_(s v) dot p_(h m)(1) = -(p_(h m)(1) dot t_(g e n) dot m_(h m)(2, 20))/(m^(s v)_(h m)) =\ = -(-0.2337t_(g e n) dot 1.8)/(-6.9) approx - 0.061t_(g e n) $<pgenus:svtotal:eq>

$ 0.054t_(g e n) - 0.061t_(g e n) < 0$ <pgenus:compare:eq>

We got that power drain for SV exceeds PG. However Music Man has progress decrease when there is no noice, maybe it helps decreasing Music Man progress? Well, no. If you play without PG and fan, using AC for coolingm, making minimal noice, playing perfectly with Lolbit and Phone Guy, Music Man still will be progress by AC noice. His calming down on hard mode is disproportionately small, compared to the progress gain. So there is no way to globally calm MM without using SV. That fact already makes 'old' strategy unoptimal powerwise. 

But this doesnt completely mean that PG is useless. It becomes useless when the player forced to calm down the Music Man using SV. The most optimal strategy for using PG is to use it only as much as necessary to avoid getting Music Man to his max aggression until the end of the night, using SV only for his special attacks.

== Music Man abuse

From the previous paragraph you learned that many conditions are needed for the rational use of PG. But there is another advanced technique that allows you to make as much noise as you want without any Music Man progression. 

There is one thing during his special attack, progress cap in $[20;80]$ range. So if Music Man is on 20 progress, you cant lower that value until you counter his special attack. And its the same for 80 progression. Вuring his special attack, regardless of the noise level, progress wont go up above 80. Therefore, the point of 'Music Man abuse' is to use noise tools(mainly PG + Fan) to the maximum during this time without any consequences. With perfect execution and rng, you can generate up to $10p_(g e n) = 0.54$ enegry per one abuse.

== 5 AM power optimizations

Overall idea of 5 AM optimizations it to edge and stall any animatronic. Most effective and important is to stall progression animatronics.

=== Lefty

From previous analysis we get $approx 11$ seconds for Lefty to progress by 1 stage. On hard mode it is depends on how often you check him, but by average it is $approx 9-10$ seconds.

We can make energy optimizations by not using GMB if we are sure that Lefty wont jumpscare us. For example if Lefty has 3 stage on 5:40, there is no point in using GMB, he cant progress to last stage in 20 seconds.

My personal playstyle is to keep Lefty on 2-3 stage before 5 AM, then force and keep him to 5 stage after 5 AM. But it is dont really important how you manage Lefty.

There are certain situations where you can *clearly* understand that you don’t need to use GMB if Lefty has $x$ stage on $y$ time.

#subfigure(
  figure(image("../images/leftystage1.png"), caption: [1 stage, Dont use GMB since 5:10]),
  figure(image("../images/leftystage2.png"), caption: [2 stage, Dont use GMB since 5:20]),
  figure(image("../images/leftystage3.png"), caption: [3 stage, Dont use GMB since 5:30]),
  figure(image("../images/leftystage4.png"), caption: [4 stage, Dont use GMB since 5:40]),
  figure(image("../images/leftystage5.png"), caption: [5 stage, Dont use GMB since 5:50]),
  figure(image("../images/leftystage6.png"), caption: [6 stage, not safe actually\*]),
  columns: (1fr, 1fr, 1fr),
  caption: [All lefty stages and corresponding them safe No-GMB time ],
  label: <5am:lefty:stages:fig>,
)

Those times are for safe playstyle, assuming Lefty to be at stage 5 at end of the night. However you can save $1%$ more power by edging Lefty on 6 stage. But this is much more difficult, so i dont recommend you to do this.

That works for both normal and hard mode (assuming you, like, check lefty often idk).

=== Jack-O-Chica

`Jack-O-Chica` is the main temperature controller, she will progress on high temperature values($ >=90$ on normal mode, $ >=80$ on hard more) and kills you when you reach a certain progress.

There wont be such a point in analyzing the progress function, the only thing you need to know is that its progression is not constant and depends only on temperature. When the temperature of progress is reached, she will progress differently: the higher the temperature, the higher the progress.

Ill just tell you how long it takes for Jack-O-Chick to fully progress, for normal mode, starting with $90 degree$ and dont use any cooling tool, you can survive for $approx 12$ seconds, for hard mode starting from $80 degree$ you can survive $approx 13$ seconds. So in any case you let Jack-O-Chica progress for the last 10 seconds of night.

=== General

You can teoretically stall any door animatronic and get power advantage, but it dont give so much power as edging Lefty or Jack-O-Chica.

== Powerpace formula

Power drain in Ultimatum is not linear for entire night. You spend less energy than average at the beginning(due coinfarming first 13 second) and end of the night(due Lefty and Jack-O-Chica edging)

Also powerpace in Ultimatum depends on many other things, mostly on Lefty stage and temperature. To calculate powerpace simply, you can normalize the energy depending on the Lefty stage/temperature. (The most important thing to consider is the Lefty stage and the temperature can generally be ignored)

To decrease Lefty progress by 1 stage you will need $approx 1%$ of power, so you can get the normalized power by subtracting the Lefty stage from it

Powerpace values a smth like that:

#let powerpacetab = {
  table(
  columns: 5,
  table.header(
    [*1 AM*],
    [*2 AM*],
    [*3 AM*],
    [*4 AM*],
    [*5 AM*],
  ),
  [$86$], [$68$], [$49$], [$31$], [$12$], 
  )
}

#figure(
    powerpacetab,
    kind: table,
    caption : [Powerpace for each hour for normalized power]
) <powerpac:temp>

